---
    - name: Ensure group 'itdep' exists
      ansible.builtin.group:
        name: itdep
        state: present

    - name: Create user 'devops'
      ansible.builtin.user:
        name: devops
        group: itdep
        create_home: yes

    - name: Set up .bashrc for user 'devops'
      ansible.builtin.copy:
        dest: "/home/devops/.bashrc"
        content: |
          # Custom .bashrc content
          export PS1="\[\e[0;33m\][\u@\h \W]\$\[\e[0m\] "  # Change command prompt color to yellow
        owner: devops
        mode: '0644'