---
  # Install MariaDB server
  - name: Install MariaDB Server
    ansible.builtin.yum:
      name: mariadb105-server
      state: present
    become: yes

  # Ensure MariaDB is running and enabled on boot
  - name: Start and enable MariaDB
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes
  
  - name: Ensure root password is set
    mysql_user:
      login_user: root
      login_password: ""
      user: root
      password: "{{ vault_mariadb_root_password }}"
      check_implicit_admin: yes
    ignore_errors: yes
  
  - name: Remove anonymous users
    mysql_user:
      login_user: root
      login_password: "{{ vault_mariadb_root_password }}"
      user: ''
      state: absent
  
  - name: Remove test database
    mysql_db:
      login_user: root
      login_password: "{{ vault_mariadb_root_password }}"
      db: test
      state: absent
  
  - name: Flush privileges
    mysql_user:
      login_user: root
      login_password: "{{ vault_mariadb_root_password }}"
      user: root
      append_privs: yes
      priv: '*.*:RELOAD'
  
  - name: Create a database named '{{ myapp_db }}'
    mysql_db:
      login_user: root
      login_password: "{{ vault_mariadb_root_password }}"
      name: "{{ myapp_db }}"
      state: present
  
  - name: Add a MariaDB user for external connections
    mysql_user:
      login_user: root
      login_password: "{{ vault_mariadb_root_password }}"
      name: "{{ myapp_db_user }}"
      password: "{{ vault_myapp_db_password }}"
      priv: "{{ myapp_db }}.*:ALL"
      host: '%'
      state: present
